const imagePath = {
  //icons of tab navigation
  Home: require('../assets/images/home3.png'),
  Profile: require('../assets/images/profile3.png'),
  Favorite: require('../assets/images/heart3.png'),
  Search: require('../assets/images/magnifier.png'),
  icon: require('../assets/images/icon.png'),
  backButtonImage: require('../assets/images/back3.png'),
  email: require('../assets/images/email.png'),
  lock: require('../assets/images/lock.png'),
  showPassword: require('../assets/images/show.png'),
  openEye: require('../assets/images/EYE.png'),
  checkgreen: require('../assets/images/checkgreen.png'),
  check: require('../assets/images/check.png'),
  uncheck: require('../assets/images/empty.png'),
  backgroundImage: require('../assets/images/splash.png'),
  largeicon: require('..//assets/images/largeicon2.png'),
  profileIcon: require('../assets/images/profile.png'),
  addPhotoIcon: require('../assets/images/edit.png'),
  nameIcon: require('../assets/images/user.png'),
  userimage: require('../assets/images/userimage.png'),
  searchIcon: require('../assets/images/search.png'),
  heartIcon: require('../assets/images/heartIcon.png'),
  dealImage: require('../assets/images/Rectangle.png'),
  GroupButton: require('../assets/images/Group.png'),
  Product: require('../assets/images/Product.png'),
  like: require('../assets/images/Like.png'),
  dislike: require('../assets/images/dislike.png'),
  sendIcon: require('../assets/images/sendIcon.png'),
  profilephoto: require('../assets/images/profilescreenimage.png'),
  //menu items
  readIcon: require('../assets/images/read.png'),
  lockIcon: require('../assets/images/lockitem.png'),
  logoutIcon: require('../assets/images/logout.png'),
  deleteIcon: require('../assets/images/delete.png'),
  infoIcon: require('../assets/images/infoitem.png'),
  actionItem: require('../assets/images/actionitem.png'),
  hamburgerIcon: require('../assets/images/more.png'),
  rightIcon: require('../assets/images/rightIcon.png'),
  camera: require('../assets/images/camera.png'),
};

export default imagePath;
